# Background and foreground colors
background = #000007
foreground = #F7F7FF

# Standard colors
palette = 0=#000007
palette = 1=#620625
palette = 2=#F7F7FF
palette = 3=#F7F7FF
palette = 4=#777692
palette = 5=#BB0d35
palette = 6=#BB0d35
palette = 7=#F7F7FF

# Bright colors
palette = 8=#63656b
palette = 9=#78072d
palette = 10=#F7F7FF
palette = 11=#F7F7FF
palette = 12=#9b99bd
palette = 13=#d70e3e
palette = 14=#d70e3e
palette = 15=#F7F7FF
