# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(777692)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}

#decoration {
#    active_opacity = 0.95
#    inactive_opacity = 0.88
#    fullscreen_opacity = 1.0
#}
