background            #000007
foreground            #F7F7FF

# black
color0  #000007
color8  #63656b

# red
color1  #620625
color9  #78072d

# green
color2  #F7F7FF
color10 #F7F7FF

# yellow
color3  #F7F7FF
color11 #F7F7FF

# blue
color4  #777692
color12 #9b99bd

# magenta
color5  #BB0d35
color13 #d70e3e

#cyan
color6  #BB0d35
color14 #d70e3e

#white
color7  #F7F7FF
color15 #F7F7FF


